remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: konikvranik Kodi repository
description: konikvranik's Kodi addons.
show_downloads: true
show_dir_listing: true
include: [ "repo/zips/**" ]